// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyAUQ2Mpvb4Hu_pOL1_FE1ZJ_PU3I6y9k',
    appId: '1:138351092990:web:3d9058cb1fd261dafaf1af',
    messagingSenderId: '138351092990',
    projectId: 'moodmate-eda80',
    authDomain: 'moodmate-eda80.firebaseapp.com',
    storageBucket: 'moodmate-eda80.firebasestorage.app',
    measurementId: 'G-2HNKXQENMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEKnOhx2ukXMjS9KvOkIjMmAFzZzwKni0',
    appId: '1:138351092990:android:b2fa82b030c35203faf1af',
    messagingSenderId: '138351092990',
    projectId: 'moodmate-eda80',
    storageBucket: 'moodmate-eda80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvp7lDqN1CBhxP-S_D3DHGj2Uvu4ZujVM',
    appId: '1:138351092990:ios:c0548561f235a7e2faf1af',
    messagingSenderId: '138351092990',
    projectId: 'moodmate-eda80',
    storageBucket: 'moodmate-eda80.firebasestorage.app',
    iosBundleId: 'com.example.exersize2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvp7lDqN1CBhxP-S_D3DHGj2Uvu4ZujVM',
    appId: '1:138351092990:ios:c0548561f235a7e2faf1af',
    messagingSenderId: '138351092990',
    projectId: 'moodmate-eda80',
    storageBucket: 'moodmate-eda80.firebasestorage.app',
    iosBundleId: 'com.example.exersize2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
      apiKey: 'AIzaSyAyAUQ2Mpvb4Hu_pOL1_FE1ZJ_PU3I6y9k',
      appId: '1:138351092990:web:a738364c44cf5059faf1af',
      messagingSenderId: '138351092990',
      projectId: 'moodmate-eda80',
      authDomain: 'moodmate-eda80.firebaseapp.com',
      storageBucket: 'moodmate-eda80.firebasestorage.app',
      measurementId: 'G-WTE0T495NS');
}
